name: Documentation

on:
  push:
    branches: [main]
    tags: ['v*']
    paths:
      - 'docs/**'
      - 'src/**'
      - 'pyproject.toml'
      - '.github/workflows/docs.yml'
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          
      - name: Set up Python
        run: uv python install 3.11
        
      - name: Install dependencies
        run: uv sync --extra docs
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        
      - name: Build documentation
        run: |
          # Build Sphinx documentation
          uv run sphinx-build docs docs/_build/html -b html -W --keep-going
          
          # Create .nojekyll file to prevent GitHub Pages from treating this as a Jekyll site
          touch docs/_build/html/.nojekyll
          
          # Add custom 404 page if it doesn't exist
          if [ ! -f "docs/_build/html/404.html" ]; then
            echo '<!DOCTYPE html><html><head><title>Page Not Found</title></head><body><h1>404 - Page Not Found</h1><p><a href="/">Return to Documentation Home</a></p></body></html>' > docs/_build/html/404.html
          fi
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4